feat: 下载任务创建流程优化与代码重构
XiaoYouChR/Ghost-Downloader-3 pull request #6
Opened 2024-08-05 07:24 UTC by PYmili

- 优化了下载任务的创建流程，实现自动识别粘贴板内容并根据文件链接智能计算默认线程数
- 新增`common/methods.py`文件，引入了粘贴板内容获取和默认线程数计算的功能
- 重写了`tool_hub`中的获取文件大小单位的方法，增强了程序的复用性和可维护性

improvement: 代码质量和项目维护性提升

- 优化了代码注释，提高了代码的可读性和易理解性
- 删除了不必要的全局变量，减少了内存占用和潜在的命名冲突

fix: 确保新功能与下载任务创建界面的兼容性

- 修改了`add_task_option_dialog.py`文件，适配了新引入的`common/methods.py`文件的功能
- 确保了下载任务创建界面与新逻辑的一致性和稳定性

此次提交通过引入智能化的下载任务创建方式和代码重构，提升了用户操作的便捷性和程序的健壮性，同时通过提高代码复用性，为未来可能的功能扩展打下了基础。

2024-08-06 03:49 UTC, XiaoYouChR requested changes

2024-08-06 03:49 UTC, XiaoYouChR commented on app/components/add_task_option_dialog.py
> +        # 提前对链接进行检查一次
应该在填入链接前用urlRe检测是否是合法链接再自动填入，而不是填入之后再判断链接是否合法。反客为主了属于是

2024-08-06 03:49 UTC, XiaoYouChR commented on app/common/methods.py
> +import time
将method.py里的功能移动到tools_hub.py或者把tools_hub.py里的功能移动到method.py

2024-08-06 03:49 UTC, XiaoYouChR commented on app/common/methods.py
> +def getResponseTime(_url: str, _headers: Union[dict, None] = None) -> float:
应该getRealUrl之后再判断延迟，因为有的网站会重定向多次，延迟差异往往很大

2024-08-06 03:49 UTC, XiaoYouChR commented on app/common/methods.py
> +        count = 16
认为过于保守😵‍💫

2024-08-06 03:49 UTC, XiaoYouChR commented on app/components/add_task_option_dialog.py
> +        ByLinkEstimateThreadCount = estimateThreadCount(self.linkTextEdit.toPlainText())
应该使用多线程进行智能线程计算，否则GUI会卡

2024-08-07 02:22 UTC, XiaoYouChR commented
当剪贴板是空的时候甚至打不开添加任务窗口

2024-08-08 11:55 UTC, DNLINYJ commented
后面的回复一股ai味（

2024-08-08 15:41 UTC, closed without merging